### ISSUE TITLE
Would you be willing to provide an example `project.yml` file for Xcodegen?

### ISSUE THREAD

**Issue by webdavis** [wojciech-kulik/xcodebuild.nvim#89]
I am currently trying to use this plugin to work on a Vapor project. Though I am struggling getting things to work.

So far I have tried to generate a `.xcodeproj` file using `xcodegen`.

Here is the `project.yml` file I am using:

```yml
---
name: hello
targets:
  hello:
    type: application
    platform: macOS
    sources: [Sources]
    settings:
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.domain.hello
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.domain.hello
    dependencies:
      - package: hello
packages:
  hello:
    path: ./
```

When running `XcodebuildSetup` I always get the error `Could not get build settings` after selecting the device.

I noticed in the discussions that you mentioned people who are using `xcodegen` to generate the project file so I was wondering if you would be able to provide an example `project.yml` to help people get up and running and maybe a brief explanation in the docs of the requirements to do so?
